param(
  [switch]$Watch
)

$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$Root = Split-Path -Parent $ScriptDir
$OutputPath = Join-Path $Root "docs\FUNCTIONS_SUMMARY.md"

function Get-RelativePath {
  param([string]$Path)
  return $Path.Substring($Root.Length + 1).Replace("\", "/")
}

function Get-SourceFiles {
  Get-ChildItem -Path $Root -Recurse -File |
    Where-Object {
      $_.FullName -notmatch "\\(\.git|\.gocache|server\.out\.log|server\.err\.log)$" -and
      $_.FullName -notmatch "\\node_modules\\" -and
      $_.FullName -notmatch "\\dist\\" -and
      $_.FullName -notmatch "\\web\\" -and
      $_.FullName -notmatch "\\docs\\FUNCTIONS_SUMMARY\.md$" -and
      $_.FullName -notmatch "\\scripts\\update-functions-summary\.ps1$" -and
      $_.Extension -in @(".go", ".js", ".html", ".css", ".txt", ".md")
    }
}

function Add-Line {
  param(
    [System.Collections.Generic.List[string]]$Lines,
    [string]$Text = ""
  )
  $Lines.Add($Text) | Out-Null
}

function New-FunctionSummary {
  $files = @(Get-SourceFiles)
  $goFiles = @($files | Where-Object { $_.Extension -eq ".go" })
  $jsFiles = @($files | Where-Object { $_.Extension -eq ".js" })
  $templateFiles = @($files | Where-Object { $_.FullName -match "\\frontend\\" -and $_.Extension -eq ".html" })

  $routes = New-Object System.Collections.Generic.List[object]
  $goFunctions = New-Object System.Collections.Generic.List[object]
  $goStructs = New-Object System.Collections.Generic.List[object]
  $jsFunctions = New-Object System.Collections.Generic.List[object]
  $templates = New-Object System.Collections.Generic.List[object]
  $dataAttrs = New-Object System.Collections.Generic.SortedSet[string]

  foreach ($file in $goFiles) {
    $relative = Get-RelativePath $file.FullName
    $lineNo = 0
    foreach ($line in Get-Content -Path $file.FullName) {
      $lineNo++
      if ($line -match '^\s*func\s+(?:\([^)]+\)\s*)?([A-Za-z_][A-Za-z0-9_]*)\s*\(') {
        $goFunctions.Add([pscustomobject]@{ File = $relative; Line = $lineNo; Name = $Matches[1] }) | Out-Null
      }
      if ($line -match '^\s*type\s+([A-Za-z_][A-Za-z0-9_]*)\s+struct\s*\{') {
        $goStructs.Add([pscustomobject]@{ File = $relative; Line = $lineNo; Name = $Matches[1] }) | Out-Null
      }
      if ($line -match 'r\.(Get|Post|Put|Patch|Delete)\("([^"]+)",\s*echoHandler\(([^),]+)') {
        $routes.Add([pscustomobject]@{ Method = $Matches[1]; Path = $Matches[2]; Handler = $Matches[3] }) | Out-Null
      }
    }
  }

  foreach ($file in $jsFiles) {
    $relative = Get-RelativePath $file.FullName
    $lineNo = 0
    foreach ($line in Get-Content -Path $file.FullName) {
      $lineNo++
      if ($line -match '^\s*(?:async\s+)?function\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(') {
        $jsFunctions.Add([pscustomobject]@{ File = $relative; Line = $lineNo; Name = $Matches[1] }) | Out-Null
      }
      foreach ($match in [regex]::Matches($line, 'data-[a-zA-Z0-9_-]+')) {
        $dataAttrs.Add($match.Value) | Out-Null
      }
    }
  }

  foreach ($file in $templateFiles) {
    $relative = Get-RelativePath $file.FullName
    if ($templates.Name -notcontains $file.Name) {
      $templates.Add([pscustomobject]@{ File = $relative; Name = $file.Name }) | Out-Null
    }
    foreach ($line in Get-Content -Path $file.FullName) {
      foreach ($match in [regex]::Matches($line, 'data-[a-zA-Z0-9_-]+')) {
        $dataAttrs.Add($match.Value) | Out-Null
      }
    }
  }

  $generatedAt = Get-Date -Format "yyyy-MM-dd HH:mm:ss zzz"
  $lines = New-Object System.Collections.Generic.List[string]
  Add-Line $lines "# Full Summary of Functions"
  Add-Line $lines ""
  Add-Line $lines "_Auto-generated by ``scripts/update-functions-summary.ps1`` on $generatedAt._"
  Add-Line $lines ""
  Add-Line $lines "To regenerate once:"
  Add-Line $lines ""
  Add-Line $lines '```powershell'
  Add-Line $lines ".\scripts\update-functions-summary.ps1"
  Add-Line $lines '```'
  Add-Line $lines ""
  Add-Line $lines "To auto-update this file when project files are created, edited, renamed, or deleted:"
  Add-Line $lines ""
  Add-Line $lines '```powershell'
  Add-Line $lines ".\scripts\update-functions-summary.ps1 -Watch"
  Add-Line $lines '```'
  Add-Line $lines ""
  Add-Line $lines "The watcher stays in the foreground until you stop it with `Ctrl+C`; this script does not start any background process by itself."
  Add-Line $lines ""
  Add-Line $lines "## Project Purpose"
  Add-Line $lines ""
  Add-Line $lines "This project is a separated Go/Chi API backend and static frontend linehaul dashboard with GORM/Postgres persistence, feature-based controller/service/repository packages, realtime events, caching, background jobs, and vanilla JavaScript for the current client."
  Add-Line $lines ""
  Add-Line $lines "## Main Workflow"
  Add-Line $lines ""
  Add-Line $lines "- `Ops PIC` and `FTE Ops` create linehaul requests."
  Add-Line $lines "- New requests start as `Pending` (`PENDING`) and appear across request views."
  Add-Line $lines "- `FTE Ops` can edit, cancel, or approve requests."
  Add-Line $lines "- Approved requests route to `FTE MM` as `Approved` (`APPROVED`)."
  Add-Line $lines "- `FTE MM` can reject back to FTE Ops, assign the truck, then assign plate details to move the request to `For Docking`."
  Add-Line $lines "- `Dock Officer` / `Doc Officer` handles `For Docking` requests by entering driver ID, LHTrip number, and docking time."
  Add-Line $lines "- Queue counts, notifications, and table statuses are shared across roles through `/api/stats` and `/api/requests`."
  Add-Line $lines ""
  Add-Line $lines "## Runtime Entry Points"
  Add-Line $lines ""
  Add-Line $lines "- `cmd/server/main.go`: backend API startup, DB connection, GORM migration, background workers, Chi setup, CORS, security headers, rate limiting, and route registration."
  Add-Line $lines '- `cmd/frontend/main.go`: local static frontend server for the `frontend` directory.'
  Add-Line $lines "- `internal/routes/routes.go`: HTTP route map."
  Add-Line $lines "- `internal/features/*`: feature packages using controller/service/repository layers."
  Add-Line $lines '- `frontend/static/app.js`: browser behavior for login, role visibility, request modals, action modals, tables, notifications, CSV export, and theme/sidebar controls.'
  Add-Line $lines ""
  Add-Line $lines "## HTTP Routes"
  Add-Line $lines ""
  Add-Line $lines "| Method | Path | Handler |"
  Add-Line $lines "|---|---|---|"
  foreach ($route in $routes) {
    Add-Line $lines ("| ``{0}`` | ``{1}`` | ``{2}`` |" -f $route.Method, $route.Path, $route.Handler)
  }
  Add-Line $lines ""
  Add-Line $lines "## Go Structs"
  Add-Line $lines ""
  Add-Line $lines "| Struct | File | Line |"
  Add-Line $lines "|---|---|---:|"
  foreach ($item in $goStructs) {
    Add-Line $lines ("| ``{0}`` | ``{1}`` | {2} |" -f $item.Name, $item.File, $item.Line)
  }
  Add-Line $lines ""
  Add-Line $lines "## Go Functions"
  Add-Line $lines ""
  Add-Line $lines "| Function | File | Line |"
  Add-Line $lines "|---|---|---:|"
  foreach ($item in $goFunctions) {
    Add-Line $lines ("| ``{0}`` | ``{1}`` | {2} |" -f $item.Name, $item.File, $item.Line)
  }
  Add-Line $lines ""
  Add-Line $lines "## JavaScript Functions"
  Add-Line $lines ""
  Add-Line $lines "| Function | File | Line |"
  Add-Line $lines "|---|---|---:|"
  foreach ($item in $jsFunctions) {
    Add-Line $lines ("| ``{0}`` | ``{1}`` | {2} |" -f $item.Name, $item.File, $item.Line)
  }
  Add-Line $lines ""
  Add-Line $lines "## Frontend Pages"
  Add-Line $lines ""
  Add-Line $lines "| Page | File |"
  Add-Line $lines "|---|---|"
  foreach ($item in $templates) {
    Add-Line $lines ("| ``{0}`` | ``{1}`` |" -f $item.Name, $item.File)
  }
  Add-Line $lines ""
  Add-Line $lines "## Key Frontend Data Attributes"
  Add-Line $lines ""
  foreach ($attr in $dataAttrs) {
    Add-Line $lines ("- ``{0}``" -f $attr)
  }
  Add-Line $lines ""
  Add-Line $lines "## Database Models"
  Add-Line $lines ""
  Add-Line $lines "- `Cluster`: cluster lookup data used by the New LH Request modal for cluster, region, dock, and backlogs mapping."
  Add-Line $lines "- `Request`: linehaul request lifecycle data, including status, truck details, plate number, driver ID, LHTrip number, and docking timestamps."
  Add-Line $lines "- `User`: role-aware login identity for `ops_pic`, `fte_ops`, `fte_mm`, and `dock_officer` / `doc_officer`."
  Add-Line $lines ""
  Add-Line $lines "## Status Values"
  Add-Line $lines ""
  Add-Line $lines "- `PENDING`: shown as `Pending`; FTE Ops queue."
  Add-Line $lines "- `APPROVED`: shown as `Approved`; FTE MM queue."
  Add-Line $lines "- `ASSIGNED`: shown as `Assigned`; plate assignment step."
  Add-Line $lines "- `FOR_DOCKING`: shown as `For Docking`; Dock Officer queue."
  Add-Line $lines "- `DOCKED`: docked truck awaiting confirmation."
  Add-Line $lines "- `CONFIRMED`: completed request."
  Add-Line $lines "- `REJECTED_BY_MM`: rejected by FTE MM and routed back to FTE Ops."
  Add-Line $lines "- `CANCELLED`: canceled request."
  Add-Line $lines ""

  $directory = Split-Path -Parent $OutputPath
  if (!(Test-Path $directory)) {
    New-Item -ItemType Directory -Path $directory | Out-Null
  }
  Set-Content -Path $OutputPath -Value $lines -Encoding UTF8
  Write-Host "Updated $OutputPath"
}

New-FunctionSummary

if ($Watch) {
  Write-Host "Watching $Root for source changes. Press Ctrl+C to stop."
  $watcher = New-Object System.IO.FileSystemWatcher
  $watcher.Path = $Root
  $watcher.IncludeSubdirectories = $true
  $watcher.EnableRaisingEvents = $true

  $action = {
    $path = $Event.SourceEventArgs.FullPath
    if ($path -match "\\docs\\FUNCTIONS_SUMMARY\.md$" -or $path -match "\\server\.(out|err)\.log$") {
      return
    }
    Start-Sleep -Milliseconds 500
    New-FunctionSummary
  }

  Register-ObjectEvent $watcher Changed -Action $action | Out-Null
  Register-ObjectEvent $watcher Created -Action $action | Out-Null
  Register-ObjectEvent $watcher Deleted -Action $action | Out-Null
  Register-ObjectEvent $watcher Renamed -Action $action | Out-Null

  while ($true) {
    Start-Sleep -Seconds 1
  }
}
